name: Test

on: [ 'push' ]

jobs:
  psalm:
    name: php unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.0
          - 8.1
        composer:
          - ""
          - "--prefer-lowest"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install
      - name: Run tests
        run: composer test
      - name: Run Unit Tests
        run: XDEBUG_MODE_COVERAGE=coverage vendor/bin/phpunit
      - name: Generate test coverage badge
        uses: ./
        with:
          coverage_badge_path: 'badge.svg'
          push_badge: true
          repo_token: ${{ secrets.GITHUB_TOKEN }